# Generated by Django 4.2 on 2023-05-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='r1_codes',
        ),
    ]
