# Generated by Django 4.2 on 2023-05-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_delete_r2_codes'),
    ]

    operations = [
    ]
