# Generated by Django 4.2 on 2023-05-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_r1code_r2code_delete_r1_codes_delete_r2_codes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='R1Code',
        ),
        migrations.DeleteModel(
            name='R2Code',
        ),
    ]
