# Generated by Django 4.2 on 2023-05-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_delete_r1code_delete_r2code'),
    ]

    operations = [
        migrations.CreateModel(
            name='R1Code',
            fields=[
                ('r_1_code', models.CharField(db_column='r_1_code', max_length=2, primary_key=True, serialize=False)),
                ('r_1_desc_en', models.CharField(db_column='r_1_desc_en', max_length=50, verbose_name='English Description')),
                ('r_1_desc_tr', models.CharField(db_column='r_1_desc_tr', max_length=50, verbose_name='Turkish Description')),
            ],
            options={
                'db_table': 'r1_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='R2Code',
            fields=[
                ('r_2_code', models.CharField(db_column='r_2_code', max_length=2, verbose_name='Code')),
                ('r_2_desc_en', models.CharField(db_column='r_2_desc_en', max_length=150, verbose_name='English Description')),
                ('r_2_desc_tr', models.CharField(db_column='r_2_desc_tr', max_length=150, verbose_name='Turkish Description')),
                ('code_r2', models.CharField(db_column='code_r2', max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'r2_code',
                'managed': False,
            },
        ),
    ]
