# Generated by Django 4.2 on 2023-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_r1code_r2code'),
    ]

    operations = [
        migrations.CreateModel(
            name='R3Code',
            fields=[
                ('r_3_code', models.CharField(db_column='r_3_code', max_length=2, verbose_name='r3_Code')),
                ('r_3_desc_en', models.CharField(db_column='r_3_desc_en', max_length=150, verbose_name='English Description')),
                ('r_3_desc_tr', models.CharField(db_column='r_3_desc_tr', max_length=150, verbose_name='Turkish Description')),
                ('code_r3', models.CharField(db_column='code_r3', max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'r3_code',
                'managed': False,
            },
        ),
    ]
