# Generated by Django 4.2 on 2023-05-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_randomtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomtext',
            old_name='question',
            new_name='question_new',
        ),
    ]
