# Generated by Django 4.2 on 2023-05-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_r1_codes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='r1_codes',
        ),
    ]
