# Generated by Django 4.2 on 2023-05-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_question_randomtext_question_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomText',
        ),
    ]
