# Generated by Django 4.2 on 2023-05-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_r2_codes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='r2_codes',
        ),
    ]
