# Generated by Django 4.2 on 2023-05-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_r2_codes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='r1_codes',
        ),
        migrations.DeleteModel(
            name='r2_codes',
        ),
    ]
