# Generated by Django 4.2 on 2023-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_delete_r1_codes_delete_r2_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='r1_codes',
            fields=[
                ('r_1_code_django', models.CharField(db_column='r_1_code', max_length=2, primary_key=True, serialize=False)),
                ('r_1_desc_en_django', models.CharField(db_column='r_1_desc_en', max_length=50)),
                ('r_1_desc_tr_django', models.CharField(db_column='r_1_desc_tr', max_length=50)),
            ],
            options={
                'db_table': 'r1_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='r2_codes',
            fields=[
                ('r_2_code_django', models.CharField(db_column='r_2_code', max_length=2)),
                ('r_2_desc_en_django', models.CharField(db_column='r_2_desc_en', max_length=150)),
                ('r_2_desc_tr_django', models.CharField(db_column='r_2_desc_tr', max_length=150)),
                ('code_r2_django', models.CharField(db_column='code_r2', max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'r2_code',
                'managed': False,
            },
        ),
    ]
